# -*- coding: utf-8 -*-
from __future__ import annotations

import json
from datetime import datetime
from pathlib import Path

import cv2
import numpy as np

from common import load_config, resolve

# PyCharm 直接运行时，在当前文件里改这些硬编码参数即可。
# 可选: fit2d / fit3d / click2d / test2d / test3d / show
CALIB_MODE = "show"
CALIB_IMAGE = r"D:\Positioning\02_annotation\images\firc_cloth_1002.jpg"
CALIB_TEST2D_U = 320.0
CALIB_TEST2D_V = 240.0
CALIB_TEST3D_X = 12.0
CALIB_TEST3D_Y = -30.0
CALIB_TEST3D_Z = 600.0

# click2d 模式下，不再走控制台输入；点击完像素点后，直接按这里的顺序匹配机器人坐标。
CLICK2D_ROBOT_POINTS: list[tuple[float, float]] = [
    # (350.2, 210.1),
    # (360.2, 210.1),
    # (370.2, 210.1),
    # (350.2, 220.1),
]


def load_point_pairs(file_path: Path, cols: int) -> np.ndarray:
    if not file_path.exists():
        raise SystemExit(f"[错误] 点对文件不存在: {file_path}")
    rows = []
    for i, line in enumerate(file_path.read_text(encoding="utf-8").splitlines(), 1):
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        vals = line.replace(",", " ").split()
        if len(vals) != cols:
            raise SystemExit(f"[错误] {file_path.name} 第 {i} 行需要 {cols} 个数字: {line}")
        rows.append([float(v) for v in vals])
    if not rows:
        raise SystemExit(f"[错误] {file_path} 中没有有效数据")
    return np.array(rows, dtype=np.float64)


def save_json(path: Path, data: dict):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, ensure_ascii=False, indent=2), encoding="utf-8")
    print(f"标定结果已保存: {path}")


def calibrate_2d(pixel_pts: np.ndarray, robot_pts: np.ndarray):
    H, _ = cv2.findHomography(
        pixel_pts.astype(np.float32).reshape(-1, 1, 2),
        robot_pts.astype(np.float32).reshape(-1, 1, 2),
        method=cv2.RANSAC,
        ransacReprojThreshold=5.0,
    )
    if H is None:
        raise SystemExit("[错误] 单应矩阵计算失败")
    pred = cv2.perspectiveTransform(pixel_pts.astype(np.float32).reshape(-1, 1, 2), H).reshape(-1, 2)
    err = np.linalg.norm(pred - robot_pts, axis=1)
    return H, float(err.mean()), float(err.max())


def fit2d(cfg: dict):
    pts = load_point_pairs(resolve(cfg["calibration"]["points_2d"]), cols=4)
    if len(pts) < 4:
        raise SystemExit("[错误] 2D 标定至少需要 4 组点")
    H, mean_e, max_e = calibrate_2d(pts[:, :2], pts[:, 2:])
    print(f"2D 标定完成: {len(pts)} 组点, 平均误差 {mean_e:.3f} mm, 最大误差 {max_e:.3f} mm")
    save_json(resolve(cfg["calibration"]["file_2d"]), {
        "type": "2d_homography",
        "units": {"image": "pixel", "robot": "mm"},
        "matrix": H.tolist(),
        "points": pts.tolist(),
        "mean_error_mm": mean_e,
        "max_error_mm": max_e,
        "created": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
    })


def click2d(cfg: dict, image_path: Path):
    img = cv2.imread(str(image_path))
    if img is None:
        raise SystemExit(f"[错误] 无法读取图片: {image_path}")

    points: list[list[int]] = []
    disp = img.copy()

    def on_mouse(event, x, y, flags, param):
        if event == cv2.EVENT_LBUTTONDOWN:
            points.append([x, y])
            cv2.circle(disp, (x, y), 4, (0, 0, 255), -1)
            cv2.putText(disp, str(len(points)), (x + 6, y - 6),
                        cv2.FONT_HERSHEY_SIMPLEX, 0.6, (0, 0, 255), 2)

    win = "click pixel points, [s]/Enter=finish  [r]=undo  [Esc]=cancel"
    cv2.namedWindow(win, cv2.WINDOW_NORMAL)
    cv2.setMouseCallback(win, on_mouse)
    while True:
        cv2.imshow(win, disp)
        key = cv2.waitKey(30) & 0xFF
        if key in (13, ord("s")):
            break
        if key == 27:
            cv2.destroyAllWindows()
            print("已取消")
            return
        if key == ord("r") and points:
            points.pop()
            disp = img.copy()
            for i, (px, py) in enumerate(points, 1):
                cv2.circle(disp, (px, py), 4, (0, 0, 255), -1)
                cv2.putText(disp, str(i), (px + 6, py - 6),
                            cv2.FONT_HERSHEY_SIMPLEX, 0.6, (0, 0, 255), 2)
    cv2.destroyAllWindows()

    if len(points) < 4:
        raise SystemExit(f"[错误] 至少需要点击 4 个点，当前只有 {len(points)} 个")
    if len(CLICK2D_ROBOT_POINTS) != len(points):
        raise SystemExit(
            f"[错误] CLICK2D_ROBOT_POINTS 数量为 {len(CLICK2D_ROBOT_POINTS)}，"
            f"但实际点击了 {len(points)} 个像素点，请先在 calibration.py 中补齐硬编码坐标。"
        )

    rows = []
    for (u, v), (x, y) in zip(points, CLICK2D_ROBOT_POINTS):
        rows.append([u, v, x, y])

    pts_file = resolve(cfg["calibration"]["points_2d"])
    lines = [
        "# 2D calibration points generated by click2d",
        "# u v X Y",
    ]
    lines += [" ".join(f"{v:g}" for v in r) for r in rows]
    pts_file.parent.mkdir(parents=True, exist_ok=True)
    pts_file.write_text("\n".join(lines), encoding="utf-8")
    print(f"点对已保存: {pts_file}")
    fit2d(cfg)


def calibrate_3d(cam_pts: np.ndarray, robot_pts: np.ndarray):
    src = cam_pts.astype(np.float32).reshape(-1, 1, 3)
    dst = robot_pts.astype(np.float32).reshape(-1, 1, 3)
    try:
        M, scale = cv2.estimateAffine3D(src, dst, force_rotation=True)
    except cv2.error as e:
        raise SystemExit(f"[错误] 3D 变换计算失败: {e}")
    M = np.asarray(M, dtype=np.float64)
    scale = float(scale)
    M[:, :3] *= scale

    T = np.vstack([M, [0, 0, 0, 1]])
    pred = (M[:, :3] @ cam_pts.T).T + M[:, 3]
    err = np.linalg.norm(pred - robot_pts, axis=1)
    return T, float(err.mean()), float(err.max()), scale


def fit3d(cfg: dict):
    pts = load_point_pairs(resolve(cfg["calibration"]["points_3d"]), cols=6)
    if len(pts) < 3:
        raise SystemExit("[错误] 3D 标定至少需要 3 组点")
    T, mean_e, max_e, scale = calibrate_3d(pts[:, :3], pts[:, 3:])
    print(f"3D 标定完成: {len(pts)} 组点, 平均误差 {mean_e:.3f} mm, 最大误差 {max_e:.3f} mm")
    print(f"尺度因子 = {scale:.6f}")
    save_json(resolve(cfg["calibration"]["file_3d"]), {
        "type": "3d_rigid_transform",
        "units": "mm",
        "matrix_4x4": T.tolist(),
        "points": pts.tolist(),
        "mean_error_mm": mean_e,
        "max_error_mm": max_e,
        "created": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
    })


def load_calib_2d(path) -> np.ndarray:
    data = json.loads(Path(path).read_text(encoding="utf-8"))
    return np.array(data["matrix"], dtype=np.float64)


def load_calib_3d(path) -> np.ndarray:
    data = json.loads(Path(path).read_text(encoding="utf-8"))
    return np.array(data["matrix_4x4"], dtype=np.float64)


def pixel_to_robot(H: np.ndarray, u: float, v: float) -> tuple[float, float]:
    p = cv2.perspectiveTransform(np.array([[[u, v]]], dtype=np.float32), H)
    return float(p[0, 0, 0]), float(p[0, 0, 1])


def cam_to_robot(T: np.ndarray, x: float, y: float, z: float) -> tuple[float, float, float]:
    p = T @ np.array([x, y, z, 1.0])
    return float(p[0]), float(p[1]), float(p[2])


def show(cfg: dict):
    for name, key in (("2D", "file_2d"), ("3D", "file_3d")):
        f = resolve(cfg["calibration"][key])
        if not f.exists():
            print(f"[{name}] 未标定 ({f})")
            continue
        d = json.loads(f.read_text(encoding="utf-8"))
        err = d.get("mean_error_mm", d.get("mean_error", "?"))
        print(f"[{name}] 已标定 {f} 时间={d.get('created')} 平均误差={err} 点数={len(d.get('points', []))}")


def test2d(cfg: dict, u: float, v: float):
    f = resolve(cfg["calibration"]["file_2d"])
    if not f.exists():
        raise SystemExit("[错误] 尚未进行 2D 标定")
    X, Y = pixel_to_robot(load_calib_2d(f), u, v)
    print(f"像素 ({u:.1f}, {v:.1f}) -> 机器人 (X={X:.2f}, Y={Y:.2f}) mm")


def test3d(cfg: dict, x: float, y: float, z: float):
    f = resolve(cfg["calibration"]["file_3d"])
    if not f.exists():
        raise SystemExit("[错误] 尚未进行 3D 标定")
    X, Y, Z = cam_to_robot(load_calib_3d(f), x, y, z)
    print(f"相机3D ({x:.1f}, {y:.1f}, {z:.1f}) mm -> 机器人 (X={X:.2f}, Y={Y:.2f}, Z={Z:.2f}) mm")


def main():
    cfg = load_config()

    if CALIB_MODE == "fit2d":
        fit2d(cfg)
    elif CALIB_MODE == "fit3d":
        fit3d(cfg)
    elif CALIB_MODE == "click2d":
        click2d(cfg, Path(CALIB_IMAGE))
    elif CALIB_MODE == "test2d":
        test2d(cfg, CALIB_TEST2D_U, CALIB_TEST2D_V)
    elif CALIB_MODE == "test3d":
        test3d(cfg, CALIB_TEST3D_X, CALIB_TEST3D_Y, CALIB_TEST3D_Z)
    elif CALIB_MODE == "show":
        show(cfg)
    else:
        raise SystemExit(f"[错误] 不支持的 CALIB_MODE: {CALIB_MODE}")


if __name__ == "__main__":
    main()
